In [1]:
import pandas as pd
import numpy as np

In [2]:
dat1=pd.read_csv('dataset/Dataset_01.csv')
dat1.head(3)

TV      Radio  Social_Media Influencer       Sales
0  16.0   6.566231      2.907983       Mega   54.732757
1  13.0   9.237765      2.409567       Mega   46.677897
2  41.0  15.886446      2.913410       Mega  150.177829

In [3]:
dat1.shape

(4572, 5)

In [5]:
dat1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4572 entries, 0 to 4571
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   TV            4562 non-null   float64
 1   Radio         4568 non-null   float64
 2   Social_Media  4566 non-null   float64
 3   Influencer    4572 non-null   object 
 4   Sales         4566 non-null   float64
dtypes: float64(4), object(1)
memory usage: 178.7+ KB


In [8]:
a1=[3,6,9, np.nan]

In [9]:
a1

[3, 6, 9, nan]

In [7]:
np.nan

nan

In [ ]:
a2=[]  #null

In [10]:
np.isnan(a1)

array([False, False, False,  True])

In [13]:
a1[3] == 'nan'

False

In [15]:
dat1.isna().sum()

TV              10
Radio            4
Social_Media     6
Influencer       0
Sales            6
dtype: int64

In [ ]:
dat1.isna().sum()

In [16]:
sum(a1)

nan

In [17]:
dat1.isna().sum(axis=1)

0       0
1       0
2       0
3       0
4       0
       ..
4567    0
4568    0
4569    0
4570    0
4571    0
Length: 4572, dtype: int64

In [18]:
dat1.isna().sum()

TV              10
Radio            4
Social_Media     6
Influencer       0
Sales            6
dtype: int64

In [19]:
dat1.isna().sum().sum()

26

In [20]:
dat1.isnull()

TV  Radio  Social_Media  Influencer  Sales
0     False  False         False       False  False
1     False  False         False       False  False
2     False  False         False       False  False
3     False  False         False       False  False
4     False  False         False       False  False
...     ...    ...           ...         ...    ...
4567  False  False         False       False  False
4568  False  False         False       False  False
4569  False  False         False       False  False
4570  False  False         False       False  False
4571  False  False         False       False  False

[4572 rows x 5 columns]

In [23]:
dat1.columns.drop('Influencer')

Index(['TV', 'Radio', 'Social_Media', 'Sales'], dtype='object')

In [24]:
q2_list=['TV', 'Radio', 'Social_Media', 'Sales']
# q2_list=dat1[q2_list].corr()

In [25]:
dat1[q2_list].corr()

TV     Radio  Social_Media     Sales
TV            1.000000  0.869460      0.528168  0.999497
Radio         0.869460  1.000000      0.607452  0.869105
Social_Media  0.528168  0.607452      1.000000  0.528906
Sales         0.999497  0.869105      0.528906  1.000000

In [26]:
dat1['TV']

0       16.0
1       13.0
2       41.0
3       83.0
4       15.0
        ... 
4567    26.0
4568    71.0
4569    44.0
4570    71.0
4571    42.0
Name: TV, Length: 4572, dtype: float64

In [ ]:
# 데이터선택
# 데이터셋명['열이름']  # 시리즈, 열이름 없음, 1d
# 데이터셋명[['열이름', '열이름']]  # 데이터프레임
# 데이터셋명[['열이름']]  # 데이터프레임, 열이름 존재, 2d
# 데이터셋명.열이름  # 열이름이 선언되어 있어야 함

# 데이터셋명.loc[ 인덱스명/'행이름' , '열이름']
# 데이터셋명.loc[ ['행이름', '행이름'] , ['열이름', '열이름']]
# 데이터셋명.loc[ 위치번호 , 컬럼위치번호]
# 데이터셋명.loc[ [인덱스번호, 인덱스번호] , [컬럼번호, 컬럼번호]]

# 데이터셋명[인덱스명:인덱스명]  # ex: 행기준 5~10, dat1[5:10]
# 데이터셋명.loc[ ['행이름', '행이름'] , '시작열이름':'끝열이름']

# 데이터셋명[조건] #  조건 결과가 데이터셋의 행의 수 만큼 리턴
# dat1[dat2.TV >= 10] # 조건의 결과가 True인 데이터만 필터링
# 데이터셋명.iloc[조건,:] # 인덱스명이 같지 않아도 작동
# 데이터셋명[조건.values]  # 인덱스명이 같지 않아도 작동

In [28]:
a1 = dat1.head(20)

In [30]:
a2=a1.drop(index=4)
a2

TV      Radio  Social_Media Influencer       Sales
0    16.0   6.566231      2.907983       Mega   54.732757
1    13.0   9.237765      2.409567       Mega   46.677897
2    41.0  15.886446      2.913410       Mega  150.177829
3    83.0  30.020028      6.922304       Mega  298.246340
5    29.0   9.614382      1.027163       Mega  105.889148
6    55.0  24.893811      4.273602      Micro  198.679825
7    31.0  17.355042      2.289855       Nano  108.733932
8    76.0  24.648898      7.130116      Macro  270.189400
9    13.0   0.431128      2.229423       Mega   48.280582
10   62.0  24.345189      5.151483       Nano  224.961019
11   42.0  15.807337      3.194925       Mega  145.543992
12   64.0  20.240424      3.921148      Micro  229.632381
13    NaN  22.351667      3.031815       Mega  276.165351
14   34.0   0.226326      2.372706       Nano  121.336419
15   36.0   3.900196      0.060402       Nano  123.526113
16   60.0  22.353721      0.940802       Mega  212.764397
17   25.0   9.905843      1.853225      Micro   89.819923
18  100.0  36.116091      3.674296      Macro  353.804639
19   92.0  40.736990      4.636564       Nano  329.350540

In [ ]:
a=dat1.copy()

In [31]:
a2.loc[5,]

TV                    29.0
Radio             9.614382
Social_Media      1.027163
Influencer            Mega
Sales           105.889148
Name: 5, dtype: object

In [32]:
a2.iloc[5,]

TV                    55.0
Radio            24.893811
Social_Media      4.273602
Influencer           Micro
Sales           198.679825
Name: 6, dtype: object

In [33]:
dat1[5:10]

TV      Radio  Social_Media Influencer       Sales
5  29.0   9.614382      1.027163       Mega  105.889148
6  55.0  24.893811      4.273602      Micro  198.679825
7  31.0  17.355042      2.289855       Nano  108.733932
8  76.0  24.648898      7.130116      Macro  270.189400
9  13.0   0.431128      2.229423       Mega   48.280582

In [36]:
dat1.loc[:,'TV':'Social_Media']

TV      Radio  Social_Media
0     16.0   6.566231      2.907983
1     13.0   9.237765      2.409567
2     41.0  15.886446      2.913410
3     83.0  30.020028      6.922304
4     15.0   8.437408      1.405998
...    ...        ...           ...
4567  26.0   4.472360      0.717090
4568  71.0  20.610685      6.545573
4569  44.0  19.800072      5.096192
4570  71.0  17.534640      1.940873
4571  42.0  15.966688      5.046548

[4572 rows x 3 columns]

In [42]:
# Q2 정답
round(dat1[q2_list].corr()['Sales'].drop('Sales').abs().max(), 4)
# 상관계수 산출->Sales열 선택-> Sales 값 제외한 가장 큰 값

0.9995

In [43]:
dat1[q2_list].corr()['Sales'].drop('Sales').abs().idxmax()

'TV'

In [44]:
dat1[q2_list].corr()['Sales'].drop('Sales').abs()

TV              0.999497
Radio           0.869105
Social_Media    0.528906
Name: Sales, dtype: float64

In [45]:
q3_list=['TV', 'Radio', 'Social_Media']

In [46]:
from sklearn.linear_model import LinearRegression

In [48]:
lm=LinearRegression(fit_intercept=True)
# lm.fit(X, y)  # X: 입력변수, 2D로 입력, 결측치 없어야 함, y: 1차원, 결측치 없어야 함ㅣ
# dat1.dropna(inplace=True)
# dat2=dat1.dropna(subset=['TV'])
# dat2=dat1.dropna(how='all/any')
dat2=dat1.dropna()
lm.fit(dat2[q3_list], dat2['Sales'])

LinearRegression()

In [49]:
lm.coef_

array([ 3.56256963, -0.00397039,  0.00496402])

In [50]:
np.sort(lm.coef_, )

array([-0.00397039,  0.00496402,  3.56256963])

In [55]:
# help(np.round)

In [57]:
q3=pd.Series(lm.coef_).sort_values(ascending=False)

In [58]:
q3

0    3.562570
2    0.004964
1   -0.003970
dtype: float64

In [61]:
np.trunc(q3*1000)/1000

0    3.562
2    0.004
1   -0.003
dtype: float64

In [63]:
pred=lm.predict(dat2[q3_list])  # 예측
dat2['Sales'] - pred  # 잔차

0      -2.122759
1       0.523171
2       4.295050
3       2.771852
4       3.316120
          ...   
4567    2.207216
4568   -3.657225
4569    7.065673
4570    0.861916
4571   -1.253204
Name: Sales, Length: 4546, dtype: float64

In [65]:
# MSE
((dat2['Sales'] - pred)**2).mean()

8.69385888471783

In [66]:
# R2
lm.score(dat2[q3_list], dat2['Sales'])

0.9989950217942258

In [69]:
from sklearn.metrics import r2_score, mean_squared_error  # 결정계수
# r2_score(목표값(실제값), 예측값)
print(r2_score(dat2['Sales'], pred))
print(mean_squared_error(dat2['Sales'], pred))

0.9989950217942258
8.69385888471783


In [70]:
pd.__version__

'2.2.2'