In [1]:
import pandas as pd
import numpy as np

In [5]:
dat10=pd.read_csv('dataset/Dataset_10.csv')
dat10.head(3)

model  engine_power  age_in_days      km  previous_owners  price  \
0  lounge            51          882   25000                1   8900   
1     pop            51         1186   32500                1   8800   
2   sport            74         4658  142228                1   4200   

   Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9  Unnamed: 10  Unnamed: 11  \
0         NaN         NaN         NaN         NaN          NaN          NaN   
1         NaN         NaN         NaN         NaN          NaN          NaN   
2         NaN         NaN         NaN         NaN          NaN          NaN   

   Unnamed: 12  Unnamed: 13  Unnamed: 14  Unnamed: 15  Unnamed: 16  
0          NaN          NaN          NaN          NaN          NaN  
1          NaN          NaN          NaN          NaN          NaN  
2          NaN          NaN          NaN          NaN          NaN

In [6]:
dat10=dat10.dropna(how='all', axis=1)
dat10.head(3)

model  engine_power  age_in_days      km  previous_owners  price
0  lounge            51          882   25000                1   8900
1     pop            51         1186   32500                1   8800
2   sport            74         4658  142228                1   4200

In [7]:
dat10.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1538 entries, 0 to 1537
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   model            1538 non-null   object
 1   engine_power     1538 non-null   int64 
 2   age_in_days      1538 non-null   int64 
 3   km               1538 non-null   int64 
 4   previous_owners  1538 non-null   int64 
 5   price            1538 non-null   int64 
dtypes: int64(5), object(1)
memory usage: 72.2+ KB


In [ ]:
# Q1

In [8]:
q1=dat10[(dat10.previous_owners == 1) & (dat10.engine_power == 51)]
len(dat10), len(q1)

(1538, 1312)

In [9]:
q1.engine_power.unique()

array([51], dtype=int64)

In [10]:
q1.previous_owners.unique()

array([1], dtype=int64)

In [11]:
q1_out=q1.groupby('model')['price'].mean()
q1_out   # 답: lounge

model
lounge    9072.819227
pop       8118.091503
sport     6719.959184
Name: price, dtype: float64

In [ ]:
# Q2

In [12]:
gr_l=dat10[dat10.model == 'lounge']['age_in_days']
gr_s=dat10[dat10.model == 'sport']['age_in_days']

In [13]:
import scipy.stats as st

In [14]:
q2_t_out=st.ttest_ind(gr_l, gr_s)
q2_t_out

TtestResult(statistic=-13.924853653047471, pvalue=6.460984425590992e-41, df=1178.0)

In [ ]:
# 해석: p-value가 유의수준 0.05보다 작으므로 귀무가설을 기각
# 이때 귀무가설은 두 집단의 평균은 같다
# 대립가설은 두 집단의 평균은 같지 않다
# 답: Y

In [ ]:
# Q3

In [15]:
q3_list=['engine_power', 'age_in_days', 'km']

In [16]:
q3=dat10[dat10.model == 'pop']

In [17]:
from sklearn.linear_model import LinearRegression

In [20]:
lm = LinearRegression().fit(q3[q3_list], q3['price'])

In [21]:
lm.predict([[51, 400, 9500]])

C:\Users\user\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([10181.39254751])

In [ ]:
# 답: 10181